/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* cells_not_processed =  1  *)
(* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:1.1-19.10" *)
module Trojan1(clk, rst, r1, trigger);
  reg \$auto$verilog_backend.cc:2184:dump_module$5  = 0;
  (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:10.2-16.6" *)
  reg [3:0] _0_;
  (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:10.2-16.6" *)
  reg [3:0] _1_;
  (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:10.2-16.6" *)
  reg [3:0] _2_;
  (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:15.27-15.41" *)
  wire [3:0] _3_;
  (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:15.8-15.15" *)
  wire _4_;
  (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:12.8-12.12" *)
  wire _5_;
  (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:2.8-2.11" *)
  input clk;
  wire clk;
  (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:8.13-8.20" *)
  reg [3:0] counter;
  (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:4.8-4.10" *)
  input r1;
  wire r1;
  (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:3.8-3.11" *)
  input rst;
  wire rst;
  (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:5.9-5.16" *)
  output trigger;
  wire trigger;
  assign _3_ = _1_ + (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:15.27-15.41" *) 1'h1;
  assign _5_ = ~ (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:12.8-12.12" *) rst;
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$5 ) begin end
    _0_ = _2_;
    (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:12.4-14.7" *)
    casez (_5_)
      /* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:12.8-12.12" */
      1'h1:
          _1_ = 4'h0;
      default:
          _1_ = counter;
    endcase
    (* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:15.4-15.42" *)
    casez (_4_)
      /* src = "/mnt/c/Users/Migue/Documents/Contest_ICCAD/trojan1.v:15.8-15.15" */
      1'h1:
          _2_ = _3_;
      default:
          _2_ = _1_;
    endcase
  end
  always @(posedge clk) begin
      counter <= _0_;
  end
  assign trigger = counter[3];
  assign _4_ = r1;
endmodule
